services:
  - type: web
    name: ctomop
    runtime: python
    buildCommand: "pip install -r requirements.txt && cd frontend && npm install && npm run build && cd .. && python manage.py collectstatic --noinput"
    startCommand: "chmod +x start.sh && ./start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ctomop-db
          property: connectionString

databases:
  - name: ctomop-db
    databaseName: ctomop
    user: ctomop
